myapp:
  who: GitHub configuration repository!!!!!
  password: s3cr3t

hello:
  message: Hello World!!!

encrypted:
  message: '{cipher}ff7c079d9a4d5f10927750f960b9a34059d72acd7aaf56fbd7adb73d93b6f08b'

greeting:
  hello: Hello, World!!!
  message: Yo

dummy:
  property: some value tweaked
---
spring:
  profiles: local
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

foo:
  bar: Profile test
  
hello:
  message: Hello cloud (DEFAULT APP)
